# Generated by Django 5.0 on 2024-01-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Party Songs'), (2, 'Indie Songs'), (3, 'Happy Songs')], default=1, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='pimage',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
