# Generated by Django 5.0 on 2024-01-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioFile',
        ),
        migrations.AddField(
            model_name='song',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='audio_files/'),
        ),
    ]
