# Generated by Django 5.0 on 2024-01-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_song_likes_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Marathi'), (2, 'Bollywood'), (3, 'Taylor Swift'), (4, 'Album')], default='', verbose_name='Category'),
        ),
    ]
