# Generated by Django 5.0 on 2024-01-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_song_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Marathi'), (2, 'Bollywood'), (3, 'Taylor Swift'), (4, 'Album')], verbose_name='Category'),
        ),
    ]
